# This file contains the whole blog. Just one file. Easier to serve properly.
* hi  :index:
this is my /new new new new/ website. it is different from the other ones since it's no longer just some dumb static files.
** :@nav:
# TODO add links to other pages here, no conditional yet
[[*How this site's language works][How this site's language works]]
** who are you :#this:
I is cookie. I am in [[https://github.com/ckiee/nixfiles/blob/master/modules/services/mailserver/util.nix][a lot of places]].
- [[https://github.com/ckiee][=@ckiee= on Github]]
- [[https://matrix.to/#/@ckie:ckie.dev][=@ckie:ckie.dev= on Matrix]]
*** how'd you get the name "cookie" :#ckname:
I have no idea, it's changed a bit over the years but I don't remember why I picked the nbsp&/c o o k i e/&nbsp specifically.
*** talk to me! :#talk:
i am online way too much. maybe send an email? =us@ckie.dev=
** this site :#site:
this site has no index listing. as you explore, the content will change with you.
** what do you do :#ckdo:
Sometimes I make things. This website is being served to you with a few thousand lines of Rust since I wrote a good-enough-for-me parser for [[https://orgmode.org/][nbsp&Org Mode&nbsp]].
*** /things???/
Yes. Things. Mostly Rust, TypeScript and Nix. [[https://github.com/ckiee/ckiesite-rs][Here's this site.]]

* How this site's language works :meta:
This site is using /Orgish/, a custom variant of [[https://orgmode.org/][nbsp&Org Mode&nbsp]]. It includes various new things suited for this site:
** =nbsp&=
You can disable line wrapping for a bit by wrapping your content in ~nbsp&~ nbsp& *hello world this won't be line wrapped! so cool! some more words! blah blah blah blah* &nbsp ~&nbsp~

* n :nav-rendergroup-test:
h
** :@nav:
b

* render test :render-test:
toplevel
# comment
# commenting words
** hello
Some text here!
*** world
..and some more text here.
*** this shouldn't be inside world
** another *one*
yeah this has some text
maybe even a /few/ *lines*?

now this has some spacing *yay*
** markup
To markup text in Org, simply surround it with one or more marker characters. *Bold*, /italic/ and _underline_ are fairly intuitive, and the ability to use +strikethrough+ is a plus.  You can _/*combine*/_ the basic markup in any order, however ~code~ and =verbatim= need to be the *_~inner-most~_* markers if they are present since their contents are interpreted =_literally_=.

#+BEGIN_SRC rust
fn main() {
    println!("Hello world!")
}
#+END_SRC
** lists
What follows is a simple list:
- Fooing
- Baring
- Bazing
